/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

/**
 *
 * @author esmer
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Manu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(855,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(245, 202, 195));
        jPanel2.setLayout(new java.awt.GridLayout(7, 6));

        jButton2.setBackground(new java.awt.Color(245, 202, 195));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("-----");
        jPanel2.add(jButton2);

        jButton4.setBackground(new java.awt.Color(245, 202, 195));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Desayuno");
        jPanel2.add(jButton4);

        jButton9.setBackground(new java.awt.Color(245, 202, 195));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Media Mañana");
        jPanel2.add(jButton9);

        jButton13.setBackground(new java.awt.Color(245, 202, 195));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("Comida");
        jPanel2.add(jButton13);

        jButton16.setBackground(new java.awt.Color(245, 202, 195));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("Merienda");
        jPanel2.add(jButton16);

        jButton19.setBackground(new java.awt.Color(245, 202, 195));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setText("Cena");
        jPanel2.add(jButton19);

        jButton18.setBackground(new java.awt.Color(245, 202, 195));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("Lunes");
        jPanel2.add(jButton18);

        jButton15.setBackground(new java.awt.Color(245, 202, 195));
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("Pan Integral con pavo");
        jPanel2.add(jButton15);

        jButton17.setBackground(new java.awt.Color(245, 202, 195));
        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setText("Fruta");
        jPanel2.add(jButton17);

        jButton14.setBackground(new java.awt.Color(245, 202, 195));
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("Pollo");
        jPanel2.add(jButton14);

        jButton12.setBackground(new java.awt.Color(245, 202, 195));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Leche cereales");
        jPanel2.add(jButton12);

        jButton11.setBackground(new java.awt.Color(245, 202, 195));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Salmón");
        jPanel2.add(jButton11);

        jButton10.setBackground(new java.awt.Color(245, 202, 195));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Martes");
        jPanel2.add(jButton10);

        jButton8.setBackground(new java.awt.Color(245, 202, 195));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Pan Integral con atún");
        jPanel2.add(jButton8);

        jButton7.setBackground(new java.awt.Color(245, 202, 195));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Fruta");
        jPanel2.add(jButton7);

        jButton6.setBackground(new java.awt.Color(245, 202, 195));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Ternera");
        jPanel2.add(jButton6);

        jButton5.setBackground(new java.awt.Color(245, 202, 195));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Fruta ");
        jButton5.setToolTipText("");
        jPanel2.add(jButton5);

        jButton3.setBackground(new java.awt.Color(245, 202, 195));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Hamburguesa");
        jPanel2.add(jButton3);

        jButton20.setBackground(new java.awt.Color(245, 202, 195));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setText("Miércoles");
        jPanel2.add(jButton20);

        jButton21.setBackground(new java.awt.Color(245, 202, 195));
        jButton21.setForeground(new java.awt.Color(0, 0, 0));
        jButton21.setText("Pan Integral con pavo");
        jPanel2.add(jButton21);

        jButton22.setBackground(new java.awt.Color(245, 202, 195));
        jButton22.setForeground(new java.awt.Color(0, 0, 0));
        jButton22.setText("Fruta");
        jPanel2.add(jButton22);

        jButton23.setBackground(new java.awt.Color(245, 202, 195));
        jButton23.setForeground(new java.awt.Color(0, 0, 0));
        jButton23.setText("Lomo");
        jPanel2.add(jButton23);

        jButton24.setBackground(new java.awt.Color(245, 202, 195));
        jButton24.setForeground(new java.awt.Color(0, 0, 0));
        jButton24.setText("Leche cereales");
        jPanel2.add(jButton24);

        jButton25.setBackground(new java.awt.Color(245, 202, 195));
        jButton25.setForeground(new java.awt.Color(0, 0, 0));
        jButton25.setText("Brócoli");
        jPanel2.add(jButton25);

        jButton26.setBackground(new java.awt.Color(245, 202, 195));
        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton26.setForeground(new java.awt.Color(0, 0, 0));
        jButton26.setText("Jueves");
        jPanel2.add(jButton26);

        jButton27.setBackground(new java.awt.Color(245, 202, 195));
        jButton27.setForeground(new java.awt.Color(0, 0, 0));
        jButton27.setText("Pan Integral con atún");
        jPanel2.add(jButton27);

        jButton28.setBackground(new java.awt.Color(245, 202, 195));
        jButton28.setForeground(new java.awt.Color(0, 0, 0));
        jButton28.setText("Fruta");
        jPanel2.add(jButton28);

        jButton29.setBackground(new java.awt.Color(245, 202, 195));
        jButton29.setForeground(new java.awt.Color(0, 0, 0));
        jButton29.setText("Solomillo");
        jPanel2.add(jButton29);

        jButton30.setBackground(new java.awt.Color(245, 202, 195));
        jButton30.setForeground(new java.awt.Color(0, 0, 0));
        jButton30.setText("Fruta ");
        jPanel2.add(jButton30);

        jButton31.setBackground(new java.awt.Color(245, 202, 195));
        jButton31.setForeground(new java.awt.Color(0, 0, 0));
        jButton31.setText("Revuelto");
        jPanel2.add(jButton31);

        jButton32.setBackground(new java.awt.Color(245, 202, 195));
        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton32.setForeground(new java.awt.Color(0, 0, 0));
        jButton32.setText("Viernes");
        jPanel2.add(jButton32);

        jButton33.setBackground(new java.awt.Color(245, 202, 195));
        jButton33.setForeground(new java.awt.Color(0, 0, 0));
        jButton33.setText("Pan Integral con pavo");
        jPanel2.add(jButton33);

        jButton34.setBackground(new java.awt.Color(245, 202, 195));
        jButton34.setForeground(new java.awt.Color(0, 0, 0));
        jButton34.setText("Fruta");
        jPanel2.add(jButton34);

        jButton35.setBackground(new java.awt.Color(245, 202, 195));
        jButton35.setForeground(new java.awt.Color(0, 0, 0));
        jButton35.setText("Ensalada pasta");
        jPanel2.add(jButton35);

        jButton36.setBackground(new java.awt.Color(245, 202, 195));
        jButton36.setForeground(new java.awt.Color(0, 0, 0));
        jButton36.setText("Leche cereales");
        jPanel2.add(jButton36);

        jButton37.setBackground(new java.awt.Color(245, 202, 195));
        jButton37.setForeground(new java.awt.Color(0, 0, 0));
        jButton37.setText("Pollo");
        jPanel2.add(jButton37);

        jButton38.setBackground(new java.awt.Color(245, 202, 195));
        jButton38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton38.setForeground(new java.awt.Color(0, 0, 0));
        jButton38.setText("Sábado");
        jPanel2.add(jButton38);

        jButton39.setBackground(new java.awt.Color(245, 202, 195));
        jButton39.setForeground(new java.awt.Color(0, 0, 0));
        jButton39.setText("Pan Integral con atún");
        jPanel2.add(jButton39);

        jButton40.setBackground(new java.awt.Color(245, 202, 195));
        jButton40.setForeground(new java.awt.Color(0, 0, 0));
        jButton40.setText("Fruta");
        jPanel2.add(jButton40);

        jButton41.setBackground(new java.awt.Color(245, 202, 195));
        jButton41.setForeground(new java.awt.Color(0, 0, 0));
        jButton41.setText("Pure verduras");
        jPanel2.add(jButton41);

        jButton42.setBackground(new java.awt.Color(245, 202, 195));
        jButton42.setForeground(new java.awt.Color(0, 0, 0));
        jButton42.setText("Fruta ");
        jPanel2.add(jButton42);

        jButton43.setBackground(new java.awt.Color(245, 202, 195));
        jButton43.setForeground(new java.awt.Color(0, 0, 0));
        jButton43.setText("Ensalada");
        jPanel2.add(jButton43);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
